site_name: RISK Network Documentation
site_url: https://github.com/riskportal/network
repo_url: https://github.com/riskportal/network-tutorial
repo_name: network-tutorial
theme:
  name: material
  custom_dir: docs/overrides
  logo: images/risk_logo.png
  favicon: images/risk_logo.ico
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: custom
      accent: light blue
    - scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - Home: index.md
  - Getting Started:
      - 0. Intro: 0_intro.md
      - 1. Installation: 1_installation.md
  - Core Features:
      - 2. Network Input: 2_network_input.md
      - 3. Annotation: 3_annotation.md
      - 4. Statistics: 4_statistics.md
      - 5. Load Graph: 5_load_graph.md
      - 6. Visualization: 6_visualization.md
      - 7. Parameters: 7_parameters.md
  - Full Tutorial (HTML): tutorial.html
  - Download Tutorial Notebook & Data: tutorial.zip
  - Interactive Quickstart (Binder): https://mybinder.org/v2/gh/riskportal/network-tutorial/HEAD?filepath=notebooks/quickstart.ipynb
extra_css:
  - stylesheets/extra.css
